<%@ Page Language="C#" MasterPageFile="~/getputs_A.master" AutoEventWireup="true" CodeFile="Administrator.aspx.cs" Inherits="Administrator" Title="getputs - Administrator" %>
<asp:Content ID="Main" ContentPlaceHolderID="Main" Runat="Server">
    
    <asp:LinkButton ID="ItemHyperLink" runat="server" OnClick="ItemHyperLink_Click">Item</asp:LinkButton>
    <asp:LinkButton ID="UserHyperLink" runat="server" OnClick="UserHyperLink_Click">User</asp:LinkButton>
    
    <br />
    <asp:TextBox ID="MaxRowsTB" runat="server" Width="54px">50</asp:TextBox>
    <asp:Label ID="MaxRowsLabel" runat="server" Text="(Max Rows to Return)"></asp:Label><br />
    <asp:Label ID="MessageLabel" runat="server" Text="..."></asp:Label><br />
    <br />
    
    <asp:GridView 
    ID="ItemGridView" 
    runat="server" 
    AllowSorting="True" 
    AutoGenerateDeleteButton="True" 
    AutoGenerateEditButton="True"
    AutoGenerateColumns="False"
    
    OnRowEditing="ItemGridView_RowEditing"
    OnRowCancelingEdit="ItemGridView_RowCancelingEdit" 
    OnRowUpdating="ItemGridView_RowUpdating"     
    OnRowUpdated="ItemGridView_RowUpdated"
    OnRowDeleting="ItemGridView_RowDeleting"
    OnSorting="ItemGridView_Sorting"
    
    Datakeynames="IID,Date,UID,NComments,Clicks,UpVotes,DownVotes,NSaved,NEMailed" 
    Visible="False" PageSize="20" 
     >
     
     
    <Columns>
       <asp:BoundField DataField="IID" HeaderText="IID" SortExpression="IID" ReadOnly="True" />
       <asp:BoundField DataField="Title" HeaderText="Title" SortExpression="Title" />
       <asp:BoundField DataField="Link"  HeaderText="Link" SortExpression="Link" />        
       
       
        <asp:TemplateField HeaderText="Text" SortExpression="Text">
            <ItemTemplate>
                <asp:Label ID="Text" Text='<%# Bind("Text") %>' runat="server"/>               
            </ItemTemplate>
        
            <EditItemTemplate>
            <asp:TextBox 
                ID="Text" Text='<%# Bind("Text") %>' Runat="Server"
                TextMode="MultiLine" Rows="4" Width="300px"/>
            </EditItemTemplate>
        </asp:TemplateField>              
              
       <asp:BoundField DataField="Date" HeaderText="Date" SortExpression="Date" ReadOnly="True"/>
       <asp:BoundField DataField="UID" HeaderText="UID" SortExpression="UID" ReadOnly="True"/>
       <asp:BoundField DataField="NComments" HeaderText="NComments" SortExpression="NComments" ReadOnly="True"/>
             
       <asp:BoundField DataField="Category" HeaderText="Category" SortExpression="Category" />
              
       <asp:BoundField DataField="Clicks" HeaderText="Clicks" SortExpression="Clicks" ReadOnly="True"/>
       <asp:BoundField DataField="UpVotes" HeaderText="Link" SortExpression="UpVotes" ReadOnly="True"/>
       <asp:BoundField DataField="DownVotes" HeaderText="Text" SortExpression="DownVotes" ReadOnly="True"/>
       
       <asp:BoundField DataField="Spam" HeaderText="Spam" SortExpression="Spam" />
       
       <asp:BoundField DataField="NSaved" HeaderText="NSaved" SortExpression="NSaved" ReadOnly="True"/>
       <asp:BoundField DataField="NEMailed" HeaderText="NEMailed" SortExpression="NEMailed" ReadOnly="True"/>
       <asp:BoundField DataField="Tags" HeaderText="Tags" SortExpression="Tags"/>
       
       <asp:BoundField DataField="INET_NTOA(IP)" HeaderText="INET_NTOA(IP)" SortExpression="INET_NTOA(IP)" ReadOnly="True"/>
    </Columns>

     
     
    </asp:GridView>
    <br />
    <asp:GridView 
    ID="UserGridView" 
    runat="server" 
    
    AllowSorting="True" 
    AutoGenerateDeleteButton="True" 
    AutoGenerateEditButton="True"
    AutoGenerateColumns="False"
    
    OnRowEditing="UserGridView_RowEditing"
    OnRowCancelingEdit="UserGridView_RowCancelingEdit" 
    OnRowUpdating="UserGridView_RowUpdating"     
    OnRowUpdated="UserGridView_RowUpdated"
    OnRowDeleting="UserGridView_RowDeleting"
    OnSorting="UserGridView_Sorting"
    
    Datakeynames="UID,Date,EMail,About" 
    
    Visible="False"
    >
    
     <Columns>
       <asp:BoundField DataField="UID" HeaderText="UID" SortExpression="UID" ReadOnly="True" />
       <asp:BoundField DataField="Date" HeaderText="Date" SortExpression="Date" ReadOnly="True"/>
       <asp:BoundField DataField="EMail"  HeaderText="EMail" SortExpression="EMail" ReadOnly="True"/>        
       <asp:BoundField DataField="About"  HeaderText="About" SortExpression="About" ReadOnly="True"/>        
              
       <asp:BoundField DataField="Admin" HeaderText="Admin" SortExpression="Admin" />
       <asp:BoundField DataField="Points" HeaderText="Points" SortExpression="Points" />       
       
       <asp:BoundField DataField="PreferredCategories"  HeaderText="PreferredCategories" SortExpression="PreferredCategories" ReadOnly="True"/>        
       <asp:BoundField DataField="Spammer"  HeaderText="Spammer" SortExpression="Spammer" />        
       
    </Columns>
    
    </asp:GridView>
    &nbsp;<br />
    
    <!-- //  getputs.item [IID, Title, Link, Text, Date, UID, NComments, Category, Clicks, UpVotes, DownVotes, Spam] -->
    
    
    <br />
    <br />
    <asp:LinkButton ID="GSBUpdateLink" runat="server" OnClick="GSBUpdateLink_Click">GSB Update</asp:LinkButton>
    <br />
    <asp:Label ID="GSBUpdateOutputLabel" runat="server" Text="..."></asp:Label><br />
    <br />
    <asp:TextBox ID="GSBTestInputTB" runat="server"></asp:TextBox>
    <br />
    <asp:LinkButton ID="GSBTestLink" runat="server" OnClick="GSBTestLink_Click">Test Link against GSB</asp:LinkButton><br />
    <asp:Label ID="GSBTestOutputLabel" runat="server" Text="..."></asp:Label><br />
    <br />
    <br />
    <br />
    <asp:CheckBoxList ID="ReloadListsCBL" runat="server">
        <asp:ListItem>BadUsers</asp:ListItem>
        <asp:ListItem>BadIPs</asp:ListItem>
        <asp:ListItem>BadSites</asp:ListItem>
        <asp:ListItem>BadDomains</asp:ListItem>
        <asp:ListItem>TagLexicon</asp:ListItem>        
    </asp:CheckBoxList>
    <asp:LinkButton ID="ReloadListsLink" runat="server" OnClick="ReloadListsLink_Click">Reload Lists</asp:LinkButton>
    <br />
    <asp:Label ID="ReloadListsOutputLabel" runat="server" Text="..."></asp:Label><br />
    

</asp:Content>

